export const dataProgramStudi = [
    {
      No: 1,
      ID_Progam_Studi: 'PS001',
      Nama_Progam_Studi: 'Teknik Informatika',
      Fakultas: 'Fakultas Teknik',
      Jumlah_Sks: 144,
    },
    {
      No: 2,
      ID_Progam_Studi: 'PS002',
      Nama_Progam_Studi: 'Manajemen',
      Fakultas: 'Fakultas Ekonomi',
      Jumlah_Sks: 132,
    },
    {
      No: 3,
      ID_Progam_Studi: 'PS003',
      Nama_Progam_Studi: 'Ilmu Komunikasi',
      Fakultas: 'Fakultas Ilmu Sosial',
      Jumlah_Sks: 128,
    },
    {
      No: 4,
      ID_Progam_Studi: 'PS004',
      Nama_Progam_Studi: 'Hukum',
      Fakultas: 'Fakultas Hukum',
      Jumlah_Sks: 136,
    },
    {
      No: 5,
      ID_Progam_Studi: 'PS005',
      Nama_Progam_Studi: 'Sistem Informasi',
      Fakultas: 'Fakultas Ilmu Komputer',
      Jumlah_Sks: 140,
    },
    {
      No: 6,
      ID_Progam_Studi: 'PS006',
      Nama_Progam_Studi: 'Kedokteran Umum',
      Fakultas: 'Fakultas Kedokteran',
      Jumlah_Sks: 180,
    },
    {
      No: 7,
      ID_Progam_Studi: 'PS007',
      Nama_Progam_Studi: 'Farmasi',
      Fakultas: 'Fakultas Farmasi',
      Jumlah_Sks: 140,
    },
    {
      No: 8,
      ID_Progam_Studi: 'PS008',
      Nama_Progam_Studi: 'Agribisnis',
      Fakultas: 'Fakultas Pertanian',
      Jumlah_Sks: 136,
    },
    {
      No: 9,
      ID_Progam_Studi: 'PS009',
      Nama_Progam_Studi: 'Psikologi',
      Fakultas: 'Fakultas Psikologi',
      Jumlah_Sks: 132,
    },
    {
      No: 10,
      ID_Progam_Studi: 'PS010',
      Nama_Progam_Studi: 'Sastra Inggris',
      Fakultas: 'Fakultas Sastra',
      Jumlah_Sks: 128,
    },
    {
      No: 11,
      ID_Progam_Studi: 'PS011',
      Nama_Progam_Studi: 'Seni Rupa',
      Fakultas: 'Fakultas Seni Rupa',
      Jumlah_Sks: 124,
    },
    {
      No: 12,
      ID_Progam_Studi: 'PS012',
      Nama_Progam_Studi: 'Teknologi Informasi Bisnis',
      Fakultas: 'Fakultas Teknologi Informasi',
      Jumlah_Sks: 136,
    },
    {
      No: 13,
      ID_Progam_Studi: 'PS013',
      Nama_Progam_Studi: 'Ilmu Komunikasi',
      Fakultas: 'Fakultas Komunikasi',
      Jumlah_Sks: 128,
    },
    {
      No: 14,
      ID_Progam_Studi: 'PS014',
      Nama_Progam_Studi: 'Manajemen Bisnis',
      Fakultas: 'Fakultas Bisnis',
      Jumlah_Sks: 132,
    },
    {
      No: 15,
      ID_Progam_Studi: 'PS015',
      Nama_Progam_Studi: 'Teknologi Industri',
      Fakultas: 'Fakultas Teknologi Industri',
      Jumlah_Sks: 140,
    },
    {
      No: 16,
      ID_Progam_Studi: 'PS016',
      Nama_Progam_Studi: 'Kedokteran Hewan',
      Fakultas: 'Fakultas Kedokteran Hewan',
      Jumlah_Sks: 180,
    },
    {
      No: 17,
      ID_Progam_Studi: 'PS017',
      Nama_Progam_Studi: 'Ilmu Kesehatan Masyarakat',
      Fakultas: 'Fakultas Ilmu Kesehatan',
      Jumlah_Sks: 136,
    },
    {
      No: 18,
      ID_Progam_Studi: 'PS018',
      Nama_Progam_Studi: 'Ilmu Keperawatan',
      Fakultas: 'Fakultas Ilmu Keperawatan',
      Jumlah_Sks: 132,
    },
    {
      No: 19,
      ID_Progam_Studi: 'PS019',
      Nama_Progam_Studi: 'Teknik Elektro',
      Fakultas: 'Fakultas Teknik Elektro',
      Jumlah_Sks: 136,
    },
    {
      No: 20,
      ID_Progam_Studi: 'PS020',
      Nama_Progam_Studi: 'Pendidikan Guru Sekolah Dasar',
      Fakultas: 'Fakultas Ilmu Pendidikan',
      Jumlah_Sks: 124,
    },
    {
      No: 21,
      ID_Progam_Studi: 'PS021',
      Nama_Progam_Studi: 'Biologi',
      Fakultas: 'Fakultas Ilmu Alam',
      Jumlah_Sks: 132,
    },
    {
      No: 22,
      ID_Progam_Studi: 'PS022',
      Nama_Progam_Studi: 'Fisika',
      Fakultas: 'Fakultas Ilmu Sains',
      Jumlah_Sks: 128,
    },
    {
      No: 23,
      ID_Progam_Studi: 'PS023',
      Nama_Progam_Studi: 'Teknik Mesin',
      Fakultas: 'Fakultas Teknik Mesin',
      Jumlah_Sks: 136,
    },
    {
      No: 24,
      ID_Progam_Studi: 'PS024',
      Nama_Progam_Studi: 'Perikanan',
      Fakultas: 'Fakultas Perikanan',
      Jumlah_Sks: 132,
    },
    {
      No: 25,
      ID_Progam_Studi: 'PS025',
      Nama_Progam_Studi: 'Teknik Sipil',
      Fakultas: 'Fakultas Teknik Sipil',
      Jumlah_Sks: 140,
    },
    {
      No: 26,
      ID_Progam_Studi: 'PS026',
      Nama_Progam_Studi: 'Ilmu Budaya',
      Fakultas: 'Fakultas Ilmu Budaya',
      Jumlah_Sks: 128,
    },
    {
      No: 27,
      ID_Progam_Studi: 'PS027',
      Nama_Progam_Studi: 'Ilmu Politik',
      Fakultas: 'Fakultas Ilmu Politik',
      Jumlah_Sks: 124,
    },
    {
      No: 28,
      ID_Progam_Studi: 'PS028',
      Nama_Progam_Studi: 'Ilmu Hukum',
      Fakultas: 'Fakultas Ilmu Hukum',
      Jumlah_Sks: 136,
    },
    {
      No: 29,
      ID_Progam_Studi: 'PS029',
      Nama_Progam_Studi: 'Teknik Kimia',
      Fakultas: 'Fakultas Teknik Kimia',
      Jumlah_Sks: 136,
    },
    {
      No: 30,
      ID_Progam_Studi: 'PS030',
      Nama_Progam_Studi: 'Peternakan',
      Fakultas: 'Fakultas Peternakan',
      Jumlah_Sks: 132,
    },
  ];

  export const namaFakultas = [
    'Fakultas Teknik',
    'Fakultas Ekonomi',
    'Fakultas Ilmu Sosial',
    'Fakultas Hukum',
    'Fakultas Ilmu Komputer',
    'Fakultas Kedokteran',
    'Fakultas Farmasi',
    'Fakultas Pertanian',
    'Fakultas Psikologi',
    'Fakultas Sastra',
  ];
  
  