'use client';

import { atom } from 'recoil';

import { TSemuaFitur } from '../../types/semuafitur';

export const semuaFiturState = atom<Array<TSemuaFitur>>({
  key: 'semua-fitur-state',
  default: [
    {
      id: 19,
      namaFitur: 'Administrasi',
      icon: '/icons/semua-fitur/konversi.svg',
      warna: '#E3FBDA',
      // slug: '/administrasi',
      slug: '/administrasi/perkuliahan',
      desc: 'Administrasi berisi informasi dan intruksi untuk mengubah dan mengupdate pilihan jurusan, data informasi pribadi, informasi keluarga, dokumen, dan berkas.',
      status: true,
    },
    {
      id: 2,
      namaFitur: 'Pelajaran-Ku',
      icon: '/icons/semua-fitur/studiku.svg',
      warna: '#FEDBD7',
      slug: '/studi-ku',
      desc: 'Pelajaran-Ku adalah tempat kamu menjalani pembelajaran saat ini, seperti ujian, tes minat & bakat, dan informasi pembelajaran akan datang, serta riwayat pembelajaran.',
      status: true,
    },
    {
      id: 3,
      namaFitur: 'PR & Tugas',
      icon: '/icons/semua-fitur/penugasan.svg',
      warna: '#FEDBD7',
      slug: '/penugasan',
      desc: 'PR & Tugas berisi daftar tugas yang diberikan, tenggat waktu, serta instruksi untuk pengumpulan dan penyelesaiannya.',
      status: true,
    },
    {
      id: 11,
      namaFitur: 'Jadwal-Ku',
      icon: '/icons/semua-fitur/jadwal-ku.svg',
      warna: '#E9F6FD',
      slug: '/kalender-saya',
      desc: 'Jadwal-Ku membantu siswa mengelola jadwal belajar, tugas, kegiatan akademik, serta tenggat waktu dan acara penting secara teratur.',
      status: false,
    },
    {
      id: 9,
      namaFitur: 'UTS & UAS',
      icon: '/icons/semua-fitur/simulasi-drill.svg',
      warna: '#E9F6FD',
      slug: '',
      // desc: 'Fitur Drill, Simulasi & Uji Kompetensi',
      desc: 'UTS & UAS berisi jadwal, panduan, dan akses ke ujian online, serta informasi hasil dan ketentuan kelulusan.',
      status: false,
    },
    {
      id: 8,
      namaFitur: 'Laboratorium',
      icon: '/icons/semua-fitur/sekilas-ilmu.svg',
      warna: '#E9F6FD',
      // slug: '/roleplay-dan-assesmen',
      slug: '',
      // desc: 'Roleplay & Assesment',
      desc: 'Laboratorium berisi tugas dan simulasi berbasis keterampilan sesuai jurusan, dilengkapi panduan dan instruksi pengerjaan.',
      status: false,
    },
    {
      id: 5,
      namaFitur: 'Nilai & Rapor',
      icon: '/icons/semua-fitur/nilai-sertifikat.svg',
      warna: '#E3FBDA',
      slug: '/nilai-dan-sertifikat?tab=nilai',
      desc: 'Nilai & Rapor berisi informasi perkembangan belajarmu lewat kumpulan nilai dan rapor setelah menyelesaikan pelajaran di fitur Pelajaran-Ku.',
      status: true,
    },
    {
      id: 10,
      namaFitur: 'Papan Skor',
      icon: '/icons/semua-fitur/papan-skor-new.svg',
      warna: '#FEF6D0',
      slug: '/papan-skor',
      desc: 'Papan Skor menampilkan peringkat dan  pencapaian siswa secara real-time, memotivasi mereka melalui gamifikasi, dan mendorong persaingan sehat.',
      status: true,
    },
    {
      id: 16,
      namaFitur: 'Try Out',
      icon: '/icons/semua-fitur/try-out.svg',
      warna: '#E3FBDA',
      slug: '/try-out',
      desc: 'Try Out berisi simulasi ujian untuk membantu siswa berlatih soal, mengukur pemahaman, dan mempersiapkan diri menghadapi ujian sebenarnya.',
      status: true,
    },
    {
      id: 17,
      namaFitur: 'Tes Minat & Bakat',
      icon: '/icons/semua-fitur/tes-minat-bakat.svg',
      warna: '#FEF6D0',
      slug: '/tes-minat-bakat',
      desc: 'Tes Minat & Bakat dapat membantu siswa mengenali potensi diri, serta merekomendasikan karier yang sesuai dengan kemampuan dan ketertarikan mereka.',
      status: true,
    },
    {
      id: 20,
      namaFitur: 'Tes Kepemimpinan',
      icon: '/icons/semua-fitur/tes-kepemimpinan.svg',
      warna: '#FEF6D0',
      slug: '/tes-kepemimpinan',
      desc: 'Tes Kepemimpinan dapat membantu siswa mengevaluasi keterampilan memimpin, mengambil keputusan, dan bekerja tim, serta pengembangan diri.',
      status: true,
    },
    {
      id: 0,
      namaFitur: 'Pelatihan Berbasis Kompetensi',
      icon: '/icons/semua-fitur/pelatihan-berbasis-kompetensi.svg',
      warna: '#E9F6FD',
      slug: '/bootcamp',
      desc: 'Pelatihan Berbasis Kompetensi membantu kamu mengembangkan keterampilan dan pengetahuan praktis sesuai kebutuhan dunia kerja.',
      status: true,
    },
    {
      id: 21,
      namaFitur: 'Tes Kemampuan Akademik dan Penyetaraan',
      icon: '/icons/semua-fitur/tes-kemampuan-akademik-penyetaraan.svg',
      warna: '#FEF6D0',
      slug: '',
      desc: 'Tes Kemampuan Akademik & Penyetaraan menyediakan informasi dan akses ujian bagi siswa sebagai syarat penyetaraan pendidikan dan perolehan ijazah.',
      status: true,
    },
    {
      id: 12,
      namaFitur: 'Acara Sekolah',
      icon: '/icons/semua-fitur/acara-sekolah.svg',
      warna: '#E9F6FD',
      slug: '',
      desc: 'Acara Sekolah menginformasikan dan mengelola kegiatan seperti seminar, lomba,, dan acara sosial, memudahkan siswa untuk mendaftar, dan berpartisipasi aktif.',
      status: false,
    },
    {
      id: 18,
      namaFitur: 'Perpustakaan',
      icon: '/icons/semua-fitur/perpustakaan.svg',
      warna: '#FEF6D0',
      slug: '/pustaka-library',
      desc: 'Perpustakaan menyediakan akses ke berbagai bahan bacaan, seperti buku, modul, dan referensi digital, yang mendukung proses belajar siswa.',
      status: true,
    },
    {
      id: 13,
      namaFitur: 'Tahukah Kamu',
      icon: '/icons/semua-fitur/tahukah-kamu.svg',
      warna: '#FEDBD7',
      slug: '/sekilas-ilmu',
      desc: 'Tahukah Kamu menyediakan informasi bermanfaat yang singkat dan ringkas, membantu siswa mengakses pengetahuan baru.',
      status: true,
    },
    {
      id: 4,
      namaFitur: 'Forum Diskusi',
      icon: '/icons/semua-fitur/ruang-diskusi.svg',
      warna: '#E3FBDA',
      slug: '/ruang-diskusi',
      desc: 'Forum Diskusi adalah tempat kamu berinteraksi, berbagi dan berdiskusi dengan sesama siswa.',
      status: true,
    },

    {
      id: 15,
      namaFitur: 'Panduan',
      icon: '/icons/semua-fitur/panduan.svg',
      warna: '#E3FBDA',
      slug: '/panduan',
      desc: 'Panduan memberikan akses mudah dan cepat untuk informasi yang dibutuhkan terkait fitur-fitur pada platform Paket-C Gratis, panduan dapat berupa video atau dokumen.',
      status: true,
    },
    {
      id: 14,
      namaFitur: 'Konsultasi & Layanan',
      icon: '/icons/semua-fitur/konsultasi-layanan.svg',
      warna: '#FEF6D0',
      slug: '',
      desc: 'Konsultasi & Layanan memungkinkan siswa mendapatkan bimbingan akademik, dukungan teknis, serta bantuan administrasi.',
      status: false,
    },
    {
      id: 22,
      namaFitur: 'Kenalan & Cari Pacar',
      icon: '/icons/semua-fitur/kenalan-cari-pacar.svg',
      warna: '#FEF6D0',
      slug: '',
      desc: 'Kenalan & Cari Pacar tempat untuk kamu yang pengen cari teman baru atau mungkin jodoh yang seru !!',
      status: true,
    },

    // {
    //   id: 1,
    //   namaFitur: 'Rencana Belajar',
    //   icon: '/icons/semua-fitur/rencana-studi.svg',
    //   warna: '#FEF6D0',
    //   slug: '/rencana-studi',
    //   desc: 'Rencana belajar adalah fitur pemilihan mata pelajaran yang akan anda ambil, dan informasi terkait pembelajaran, untuk anda pilih.',
    //   status: true,
    // },

    // {
    //   id: 6,
    //   namaFitur: 'Konversi SKS',
    //   icon: '/icons/semua-fitur/konversi.svg',
    //   warna: '#E9F6FD',
    //   slug: '',
    //   desc: 'Konversi SKS membuat pembelajaran di KG bisa kamu konversi menjadi SKS (Satuan Kredit Semester) di Kampus asal, atau di tabung menjadi SKS siap konversi pada program RPL (maksimal 105 SKS). Guna memuluskan konversi SKS mu, segera usulkan kampus pilihan RPL mu nanti menjadi Mitra KG.',
    //   status: false,
    // },

    // {
    //   id: 7,
    //   namaFitur: 'Analitik',
    //   icon: '/icons/semua-fitur/analitik.svg',
    //   warna: '#FEDBD7',
    //   slug: '',
    //   desc: 'Fitur analitik berfungsi menyajikan dan menganalisis data, terkait aktivitas dan kinerja pengguna, kualitas belajar dan program belajar, di platform Paket-C Gratis paket c.',
    //   status: false,
    // },
  ],
});

export const querySemuaFitur = atom({
  key: 'query-semua-fitur',
  default: '',
});
