export enum PartnersCategoryNameEnum {
  BUMN = 'BUMN',
  PERUSAHAAN_TERBUKA = 'PERUSAHAAN_TERBUKA',
  UMKM = 'UMKM',
  PERUSAHAAN_MULTINASIONAL = 'PERUSAHAAN_MULTINASIONAL',
  YAYASAN = 'YAYASAN',
  PERUSAHAAN_TERTUTUP = 'PERUSAHAAN_TERTUTUP',
  INSTANSI_PEMERINTAHAN = 'INSTANSI_PEMERINTAHAN',
  INSTANSI_MULTILATERAL = 'INSTANSI_MULTILATERAL',
  PERGURUAN_TINGGI = 'PERGURUAN_TINGGI',
  OTHER = 'OTHER'
}
