export const dataFakultas = [
    {
      No: 1,
      ID_Fakultas: 'F001',
      Nama_Fakultas: 'Fakultas Teknik',
      Jumlah_Prodi: 5,
    },
    {
      No: 2,
      ID_Fakultas: 'F002',
      Nama_Fakultas: 'Fakultas Ekonomi',
      Jumlah_Prodi: 4,
    },
    {
      No: 3,
      ID_Fakultas: 'F003',
      Nama_Fakultas: 'Fakultas Ilmu Sosial',
      Jumlah_Prodi: 3,
    },
    {
      No: 4,
      ID_Fakultas: 'F004',
      Nama_Fakultas: 'Fakultas Hukum',
      Jumlah_Prodi: 2,
    },
    {
      No: 5,
      ID_Fakultas: 'F005',
      Nama_Fakultas: 'Fakultas Ilmu Komputer',
      Jumlah_Prodi: 6,
    },
    {
      No: 6,
      ID_Fakultas: 'F006',
      Nama_Fakultas: 'Fakultas Kedokteran',
      Jumlah_Prodi: 5,
    },
    {
      No: 7,
      ID_Fakultas: 'F007',
      Nama_Fakultas: 'Fakultas Farmasi',
      Jumlah_Prodi: 2,
    },
    {
      No: 8,
      ID_Fakultas: 'F008',
      Nama_Fakultas: 'Fakultas Pertanian',
      Jumlah_Prodi: 4,
    },
    {
      No: 9,
      ID_Fakultas: 'F009',
      Nama_Fakultas: 'Fakultas Psikologi',
      Jumlah_Prodi: 3,
    },
    {
      No: 10,
      ID_Fakultas: 'F010',
      Nama_Fakultas: 'Fakultas Sastra',
      Jumlah_Prodi: 2,
    },
    {
      No: 11,
      ID_Fakultas: 'F011',
      Nama_Fakultas: 'Fakultas Seni Rupa',
      Jumlah_Prodi: 1,
    },
    {
      No: 12,
      ID_Fakultas: 'F012',
      Nama_Fakultas: 'Fakultas Teknologi Informasi',
      Jumlah_Prodi: 3,
    },
    {
      No: 13,
      ID_Fakultas: 'F013',
      Nama_Fakultas: 'Fakultas Komunikasi',
      Jumlah_Prodi: 2,
    },
    {
      No: 14,
      ID_Fakultas: 'F014',
      Nama_Fakultas: 'Fakultas Bisnis',
      Jumlah_Prodi: 4,
    },
    {
      No: 15,
      ID_Fakultas: 'F015',
      Nama_Fakultas: 'Fakultas Teknologi Industri',
      Jumlah_Prodi: 3,
    },
    {
      No: 16,
      ID_Fakultas: 'F016',
      Nama_Fakultas: 'Fakultas Kedokteran Hewan',
      Jumlah_Prodi: 2,
    },
    {
      No: 17,
      ID_Fakultas: 'F017',
      Nama_Fakultas: 'Fakultas Ilmu Kesehatan',
      Jumlah_Prodi: 5,
    },
    {
      No: 18,
      ID_Fakultas: 'F018',
      Nama_Fakultas: 'Fakultas Ilmu Keperawatan',
      Jumlah_Prodi: 4,
    },
    {
      No: 19,
      ID_Fakultas: 'F019',
      Nama_Fakultas: 'Fakultas Teknik Elektro',
      Jumlah_Prodi: 3,
    },
    {
      No: 20,
      ID_Fakultas: 'F020',
      Nama_Fakultas: 'Fakultas Ilmu Pendidikan',
      Jumlah_Prodi: 2,
    },
    {
      No: 21,
      ID_Fakultas: 'F021',
      Nama_Fakultas: 'Fakultas Ilmu Alam',
      Jumlah_Prodi: 4,
    },
    {
      No: 22,
      ID_Fakultas: 'F022',
      Nama_Fakultas: 'Fakultas Ilmu Sains',
      Jumlah_Prodi: 3,
    },
    {
      No: 23,
      ID_Fakultas: 'F023',
      Nama_Fakultas: 'Fakultas Teknik Mesin',
      Jumlah_Prodi: 2,
    },
    {
      No: 24,
      ID_Fakultas: 'F024',
      Nama_Fakultas: 'Fakultas Perikanan',
      Jumlah_Prodi: 3,
    },
    {
      No: 25,
      ID_Fakultas: 'F025',
      Nama_Fakultas: 'Fakultas Teknik Sipil',
      Jumlah_Prodi: 4,
    },
    {
      No: 26,
      ID_Fakultas: 'F026',
      Nama_Fakultas: 'Fakultas Ilmu Budaya',
      Jumlah_Prodi: 2,
    },
    {
      No: 27,
      ID_Fakultas: 'F027',
      Nama_Fakultas: 'Fakultas Ilmu Politik',
      Jumlah_Prodi: 1,
    },
    {
      No: 28,
      ID_Fakultas: 'F028',
      Nama_Fakultas: 'Fakultas Ilmu Hukum',
      Jumlah_Prodi: 3,
    },
    {
      No: 29,
      ID_Fakultas: 'F029',
      Nama_Fakultas: 'Fakultas Teknik Kimia',
      Jumlah_Prodi: 2,
    },
    {
      No: 30,
      ID_Fakultas: 'F030',
      Nama_Fakultas: 'Fakultas Peternakan',
      Jumlah_Prodi: 4,
    },
  ];
  