export const dataDetailKonversi = {
  data: {
    major: 'UI/UX Design',
    meetLists: [
      {
        name: 'Pertemuan 1',
        modulAmount: 2,
        modulDuration: 3600,
        jurnalAmount: 2,
        totalReadJurnalTime: 3600,
        totalTask: 2,
        timeTaskDuration: 3600,
        totalGroupTask: 2,
      },
      {
        name: 'Pertemuan 2',
        modulAmount: 2,
        modulDuration: 3600,
        jurnalAmount: 2,
        totalReadJurnalTime: 3600,
        totalTask: 2,
        timeTaskDuration: 3600,
        totalGroupTask: 2,
      },
      {
        name: 'Pertemuan 3',
        modulAmount: 2,
        modulDuration: 3600,
        jurnalAmount: 2,
        totalReadJurnalTime: 3600,
        totalTask: 2,
        timeTaskDuration: 3600,
        totalGroupTask: 2,
      },
      {
        name: 'Pertemuan 4',
        modulAmount: 2,
        modulDuration: 3600,
        jurnalAmount: 2,
        totalReadJurnalTime: 3600,
        totalTask: 2,
        timeTaskDuration: 3600,
        totalGroupTask: 2,
      },
      {
        name: 'Pertemuan 5',
        modulAmount: 2,
        modulDuration: 3600,
        jurnalAmount: 2,
        totalReadJurnalTime: 3600,
        totalTask: 2,
        timeTaskDuration: 3600,
        totalGroupTask: 2,
      },
      {
        name: 'Pertemuan 6',
        modulAmount: 2,
        modulDuration: 3600,
        jurnalAmount: 2,
        totalReadJurnalTime: 3600,
        totalTask: 2,
        timeTaskDuration: 3600,
        totalGroupTask: 2,
      },
      {
        name: 'Pertemuan 7',
        modulAmount: 2,
        modulDuration: 3600,
        jurnalAmount: 2,
        totalReadJurnalTime: 3600,
        totalTask: 2,
        timeTaskDuration: 3600,
        totalGroupTask: 2,
      },
      {
        name: 'Pertemuan 8',
        modulAmount: 2,
        modulDuration: 3600,
        jurnalAmount: 2,
        totalReadJurnalTime: 3600,
        totalTask: 2,
        timeTaskDuration: 3600,
        totalGroupTask: 2,
      },
      {
        name: 'Pertemuan ',
        modulAmount: 2,
        modulDuration: 3600,
        jurnalAmount: 2,
        totalReadJurnalTime: 3600,
        totalTask: 2,
        timeTaskDuration: 3600,
        totalGroupTask: 2,
      },
      {
        name: 'Pertemuan 1',
        modulAmount: 2,
        modulDuration: 3600,
        jurnalAmount: 2,
        totalReadJurnalTime: 3600,
        totalTask: 2,
        timeTaskDuration: 3600,
        totalGroupTask: 2,
      },
      {
        name: 'Pertemuan 1',
        modulAmount: 2,
        modulDuration: 3600,
        jurnalAmount: 2,
        totalReadJurnalTime: 3600,
        totalTask: 2,
        timeTaskDuration: 3600,
        totalGroupTask: 2,
      },
    ],
    assignmentScores: [
      {
        name: 'Pertemuan 1',
        tugas: '80',
        quiz: '90',
        discuss: '80',
        active: '90',
        midTask: '100',
        finalTask: '40',
      },
      {
        name: 'Pertemuan 2',
        tugas: '80',
        quiz: '90',
        discuss: '80',
        active: '90',
        midTask: '100',
        finalTask: '40',
      },
      {
        name: 'Pertemuan 3',
        tugas: '80',
        quiz: '90',
        discuss: '80',
        active: '90',
        midTask: '100',
        finalTask: '40',
      },
      {
        name: 'Pertemuan 4',
        tugas: '80',
        quiz: '90',
        discuss: '80',
        active: '90',
        midTask: '100',
        finalTask: '40',
      },
      {
        name: 'Pertemuan 5',
        tugas: '80',
        quiz: '90',
        discuss: '80',
        active: '90',
        midTask: '100',
        finalTask: '40',
      },
      {
        name: 'Pertemuan 6',
        tugas: '80',
        quiz: '90',
        discuss: '80',
        active: '90',
        midTask: '100',
        finalTask: '40',
      },
      {
        name: 'Pertemuan 7',
        tugas: '80',
        quiz: '90',
        discuss: '80',
        active: '90',
        midTask: '100',
        finalTask: '40',
      },
      {
        name: 'Pertemuan 8',
        tugas: '80',
        quiz: '90',
        discuss: '80',
        active: '90',
        midTask: '100',
        finalTask: '40',
      },
      {
        name: 'Pertemuan 9',
        tugas: '80',
        quiz: '90',
        discuss: '80',
        active: '90',
        midTask: '100',
        finalTask: '40',
      },
      {
        name: 'Pertemuan 10',
        tugas: '80',
        quiz: '90',
        discuss: '80',
        active: '90',
        midTask: '100',
        finalTask: '40',
      },
      {
        name: 'Pertemuan 11',
        tugas: '80',
        quiz: '90',
        discuss: '80',
        active: '90',
        midTask: '100',
        finalTask: '40',
      },
    ],
  },
};

export const assignmentTableHeader = [
  'No',
  'Pertemuan',
  'Tugas',
  'Quiz',
  'Modul',
  'Tugas Tengah Semester',
  'Tugas Akhir Semester',
  'Rata-Rata Penilaian',
];

export const tableHeader = [
  'No',
  'Pertemuan',
  'Jumlah Modul Video',
  'Waktu Menonton Video',
  'Jumlah Jurnal',
  'Waktu Membaca Jurnal',
  'Penugasan Individu',
  'Waktu Pengerjaan Penugasan Individu',
  'Penugasan kelompok',
];

export const tablePembelajaranHeader = ['No', 'Kriteria Penilaian', 'Nilai'];

export const tableKriteriaPembelajaran = [
  'Mampu Membuat desain yang berpusat pada pengguna dengan memahami persyaratan project, dan umpan balik pengguna.',
  'Mampu Membuat alur pengguna, kerangka gambar, protipe, dan market',
  'Membuat Prototype dari design UI yang telah dibuat',
  'Mampu mengidentifikasi dan memecahkan masalah UX desain (data tanggap)',
  'Memiliki kemampuan berkomunikasi secara visual melalui design UI/UX',
  'Kemampuan berkomunikasi efektif: baik secara interpersonal dan digital',
];
