export const pustakaLibraryBreadCumbs = [
  {
    name: 'Beranda',
    link: '/beranda',
  },
  {
    name: 'Perpustakaan',
    link: '/pustaka-library',
  },
];

export const contentCategories = ['Jurnal', 'E-book'];

export const yearsContent = ['2025', '2024', '2023'];

export const sectionContent = [
  'Baru Rilis',
  'Topik Trending',
  'Katalog Perpustakaan',
];

export const dummyContent = [
  {
    id: 1,
    slug: 'identifikasi-secara-kimia-gugus-fungsi-senyawa-organik',
    title: 'Identifikasi Secara Kimia Gugus Fungsi Senyawa Organik',
    author:
      'Candra Irawan, Imalia Dwi Putri, Lintannisa Rahmatia, Andita Utami',
    publicationDate: 'Mar 2025',
    category: 'E-book',
    thumbnail:
      '/images/pustaka-library/ebook-25-identifikasi-secara-kimia-gugus-fungsi-senyawa-organik.png',
    pdfLink:
      'https://www.google.co.id/books/edition/Identifikasi_Secara_Kimia_Gugus_Fungsi_S/Ob1QEQAAQBAJ?hl=en&gbpv=1',
    detailLink: '/detail/1',
    abstract: `Buku kategori kimia berjudul Identifikasi Secara Kimia Gugus Fungsi Senyawa Organik merupakan karya Candra Irawan, Imalia Dwi Putri, Lintannisa Rahmatia dan Andita Utami. Buku ini merupakan kompetensi knowledge dan skill yang menjadi dasar praktik berbasis kimia organik, meliputi pengetahuan dan kemampuan dalam mengidentifikasi dan membedakan senyawa organik golongan Hidrokarbon; Alkohol dan Fenol; Eter; Aldehida dan Keton; Asam Karboksilat dan Derivatnya; Halogen Organik; Amina; Sulfonamida, Asam Sulfonat, dan Sulfonil Klorida; Karbohidrat; Lemak dan Minyak; serta Protein. Salah satu keunggulan buku ini adalah pembaca lebih mudah memahami isinya untuk diterapkan pada praktik.`,
    totalPages: 215,
    publisher: 'Deepublish',
    yearPublished: 2025,
    doi: 'https://www.google.co.id/books/edition/Identifikasi_Secara_Kimia_Gugus_Fungsi_S/Ob1QEQAAQBAJ?hl=en&gbpv=0',
    isTrending: false,
    isNewRelease: true,
  },
  {
    id: 2,
    slug: 'kimia-organik-dasar',
    title: 'Kimia Organik Dasar',
    author:
      'Andi Budirohmi, Megawati Megawati, Hestina Hestina, Hendri Satria kamal Uyun',
    publicationDate: 'Jan 2025',
    category: 'E-book',
    thumbnail: '/images/pustaka-library/ebook-25-kimia-organik-dasar.png',
    pdfLink:
      'https://books.google.co.id/books?id=s-JBEQAAQBAJ&printsec=frontcover#v=onepage&q&f=false',
    detailLink: '/detail/2',
    abstract: `Buku "Kimia Organik Dasar" menyajikan pemahaman fundamental mengenai kimia organik, yang merupakan cabang ilmu kimia yang mempelajari senyawa karbon dan reaksi-reaksi kimianya. Dalam buku ini, pembaca akan diperkenalkan dengan konsep-konsep dasar seperti struktur dan ikatan kimia, isomerisme, serta sifat-sifat umum senyawa organik. Pembahasan dimulai dari molekul sederhana, seperti alkana, alkena, dan alkuna, serta dilanjutkan dengan struktur lebih kompleks seperti alkohol, asam karboksilat, dan amina. Dengan bahasa yang sederhana dan ilustrasi yang jelas, buku ini bertujuan untuk memberikan dasar yang kuat bagi mahasiswa atau pembaca yang baru mempelajari kimia organik. Selain itu, buku ini juga mengupas tentang mekanisme reaksi kimia organik, termasuk reaksi substitusi, adisi, eliminasi, dan reaksi redoks yang terjadi pada senyawa karbon. Penekanan diberikan pada pemahaman konsep-konsep kunci yang membantu menjelaskan bagaimana senyawa organik bereaksi dalam berbagai kondisi. Dengan dilengkapi contoh-contoh soal dan latihan, buku ini juga bertujuan untuk melatih kemampuan analisis kimia organik, yang sangat penting bagi para pelajar, praktisi, maupun peneliti yang ingin menguasai bidang kimia organik sebagai dasar untuk penerapan lebih lanjut dalam ilmu farmasi, biokimia, dan industri kimia.`,
    totalPages: 129,
    publisher: 'Yayasan Tri Edukasi Ilmiah',
    yearPublished: 2025,
    doi: 'https://books.google.co.id/books?id=s-JBEQAAQBAJ&printsec=frontcover#v=onepage&q&f=false',
    isTrending: false,
    isNewRelease: true,
  },
  {
    id: 3,
    slug: 'manajemen-mutu-pendidikan-strategi-penjaminan-dan-peningkatan-mutu-di-lembaga-pendidikan',
    title:
      'Manajemen Mutu Pendidikan : Strategi Penjaminan dan Peningkatan Mutu di Lembaga Pendidikan',
    author: 'Dr. Lilis Kholisoh Nuryani, M.Pd',
    publicationDate: 'Jan 2025',
    category: 'E-book',
    thumbnail:
      '/images/pustaka-library/ebook-25-manajemen-mutu-pendidikan-strategi-penjaminan-dan-peningkatan-mutu-di-lembaga-pendidikan.png',
    pdfLink:
      'https://www.google.co.id/books/edition/Manajemen_Mutu_Pendidikan_Strategi_Penja/7uc8EQAAQBAJ?hl=en&gbpv=1&kptab=overview',
    detailLink: '/detail/3',
    abstract: `Buku ini menyajikan pembahasan mendalam mengenai konsep, prinsip, serta praktik manajemen mutu pendidikan dalam konteks lembaga pendidikan. Penulis mengulas berbagai strategi yang dapat diterapkan untuk menjamin dan meningkatkan mutu pendidikan di berbagai jenjang, baik di sekolah, madrasah, maupun lembaga pendidikan tinggi. Dalam buku ini, manajemen mutu dijelaskan sebagai suatu proses yang terus-menerus untuk memastikan kualitas pendidikan yang dihasilkan memenuhi standar yang ditetapkan, baik dari segi kurikulum, pengajaran, evaluasi dan hasil pembelajaran. Dengan pendekatan yang berbasis pada teori dan praktik, buku ini memberikan panduan praktis bagi para pendidik, pengelola pendidikan, serta pemangku kebijakan untuk merancang dan mengimplementasikan sistem manajemen mutu yang efektif.`,
    totalPages: 192,
    publisher: 'Indonesia Emas Group',
    yearPublished: 2025,
    doi: 'https://www.google.co.id/books/edition/Manajemen_Mutu_Pendidikan_Strategi_Penja/7uc8EQAAQBAJ?hl=en&gbpv=0&kptab=overview',
    isTrending: false,
    isNewRelease: true,
  },
  {
    id: 4,
    slug: 'pengantar-ekonomi-makro',
    title: 'PENGANTAR EKONOMI MAKRO',
    author:
      'Tri Haryanto, Qurrotinna Yunnisa, Ahmad Hudaifah, Shochrul Rohmatul Ajija',
    publicationDate: 'Mar 2025',
    category: 'E-book',
    thumbnail: '/images/pustaka-library/ebook-25-pengantar-ekonomi-makro.png',
    pdfLink:
      'https://www.google.co.id/books/edition/PENGANTAR_EKONOMI_MAKRO/V7xPEQAAQBAJ?hl=en&gbpv=1',
    detailLink: '/detail/4',
    abstract: `Dari sekian banyak literatur ekonomi makro yang tersedia, buku ini memiliki keunggulan tersendiri karena dibahasakan dalam kalimat yang lugas sehingga diharapkan bisa dipahami secara lebih mudah untuk para pembelajar ekonomi makro pemula terutama untuk siswa SMA dan mahasiswa semester awal. Bagi siswa SMA yang Tengah mempersiapkan diri mengikuti olimpiade ekonomi, buku ini sangat tepat karena materinya sangat lengkap. Selain itu, buku ini juga sangat cocok untuk para pengajar pengantar ekonomi makro karena dilengkapi dengan kunci jawaban yang sangat lengkap di setiap soal latihannya.`,
    totalPages: 289,
    publisher: 'Airlangga University Press',
    yearPublished: 2025,
    doi: 'https://www.google.co.id/books/edition/PENGANTAR_EKONOMI_MAKRO/V7xPEQAAQBAJ?hl=en&gbpv=0',
    isTrending: false,
    isNewRelease: true,
  },
  {
    id: 5,
    slug: 'memahami-ai-sebuah-panduan-etik',
    title: 'Memahami AI: Sebuah Panduan Etik',
    author: 'Agus Sudibyo',
    publicationDate: 'Nov 2024',
    category: 'E-book',
    thumbnail:
      '/images/pustaka-library/ebook-24-memahami-ai-sebuah-panduan-etik.png',
    pdfLink:
      'https://www.google.co.id/books/edition/Memahami_AI_Sebuah_Panduan_Etik/GYszEQAAQBAJ?hl=en&gbpv=1',
    detailLink: '/detail/5',
    abstract: `TEKNOLOGI AI generatif telah mengguncang dunia. Hanya dengan memasukkan satu pertanyaan atau perintah dalam prompt Chatgpt, kita dapat memperoleh informasi secara cepat, instan, terstruktur, dan nyaris sempurna. Bahkan teknologi ini mampu meminimalkan proses kreatif lahirnya suatu gambar, desain, video, cerita pendek, sajak, lirik lagu, bahkan nada-nada. Para profesional yang senantiasa dikejar tenggat waktu, AI generatif seperti mukzijat yang turun dari langit. Mahasiswa, dosen, penulis, peneliti, wartawan, analis, kreator konten, desainer sangat dimudahkan dalam pekerjaannya. Namun, ketika Chatgpt telah menjadi “barang publik” yang sangat populer, sejumlah kalangan mulai mencemaskan dampak negatifnya. Ketika anak-anak SMU menggunakan mesin AI untuk mengerjakan tugas matematika yang dikumpulkan besok pagi, ketika mahasiswa dapat menggunakan Chatgpt untuk menulis makalah yang selesai hanya dalam satu jam, apakah ini benar-benar baik bagi tujuan-tujuan pendidikan? Ketika seorang wartawan menyebarkan berita yang sepenuhnya atau sebagian besar dibuat oleh Chatgpt, apakah ini juga baik untuk pelembagaan jurnalisme yang beradab? Bagaimana kita menegakkan nilai tanggung jawab intelektual, integritas akademik atau moralitas publik pada era di mana pemanfaatan dan pendaurulangan diam-diam konten atau karya milik orang lain terjadi begitu massif, sistemik dan bahkan tanpa kejujuran? Memahami AI: Sebuah Panduan Etis disajikan sebagai sumbangan untuk gerakan literasi AI di Indonesia.`,
    totalPages: 200,
    publisher: 'Kepustakaan Populer Gramedia',
    yearPublished: 2024,
    doi: 'https://www.google.co.id/books/edition/Memahami_AI_Sebuah_Panduan_Etik/GYszEQAAQBAJ?hl=en&gbpv=0',
    isTrending: true,
    isNewRelease: false,
  },
  {
    id: 6,
    slug: 'pengelolaan-waktu-belajar-mengajar-strategi-inovatif-pembelajaran-berpusat-pada-siswa',
    title:
      'Pengelolaan Waktu Belajar-Mengajar Strategi Inovatif Pembelajaran Berpusat Pada Siswa',
    author: 'Prof. Dr. Suratno, M.Pd.',
    publicationDate: 'Jun 2024',
    category: 'E-book',
    thumbnail:
      '/images/pustaka-library/ebook-24-pengelolaan-waktu-belajar-mengajar-strategi-inovatif-pembelajaran-berpusat-pada-siswa.png',
    pdfLink:
      'https://www.google.co.id/books/edition/Pengelolaan_Waktu_Belajar_Mengajar_Strat/5iowEQAAQBAJ?hl=en&gbpv=1',
    detailLink: '/detail/6',
    abstract: `Buku Keguruan ini yang berjudul Buku Pengelolaan Waktu Belajar-Mengajar Strategi Inovatif Pembelajaran Berpusat Pada Siswa karya Prof. Dr. Suratno,M.Pd. Buku ini berisi paparan tentang sekelumit sorotan perbuatan guru dalam mengelola kelas ditinjau dari sudut pandang kompetensi mengelola waktu proses belajar mengajar di kelas. Satuan waktu per jam pelajaran tidak banyak, yakni hanya 45 menit. Kehadiran sosok guru di dalam kelas selama 45 menit serba unik, terkadang terpotret larut dalam kondisi alami yang muncul di dalam kelas mengikuti kemauan siswa, tetapi juga terkadang guru dapat melakukan intervensi sedemikian rupa melalui strategi pengelolaan waktu belajar-mengajar yang ada untuk dimanfaatkan secara efektif melibatkan siswa baik emosi maupun psikomotoriknya sehingga sejalan dengan asas student centered learning (SCL) yang memungkinkan berdampak efektif bagi pengembangan kemampuan 4C (critical thinking, creativity, communication, dan collaboration).`,
    totalPages: 146,
    publisher: 'Deepublish',
    yearPublished: 2024,
    doi: 'https://www.google.co.id/books/edition/Pengelolaan_Waktu_Belajar_Mengajar_Strat/5iowEQAAQBAJ?hl=en&gbpv=0',
    isTrending: true,
    isNewRelease: false,
  },
  {
    id: 7,
    slug: 'intensif-bedah-materi-dan-soal-utbk-snbt-2024',
    title: 'Intensif Bedah Materi Dan Soal UTBK-SNBT 2024',
    author:
      'Yogi Lesmana, S.T., MM, Herman Huang, M.Sc., MBA., A.C. Mahendra. K. Datu, Ph.D. Muhammad Khairul Ihsan, S.Si. Dimas Widianto Ramadhan, S.Si., Cahyarani Paramesti, S.Si., Suci Nadilla Aryandini, S.Pd., Melati Nurjana, S.S., Ananda Restiana Khoirunisa, S.Pd.',
    publicationDate: 'Mar 2024',
    category: 'E-book',
    thumbnail:
      '/images/pustaka-library/ebook-24-intensif-bedah-materi-dan-soal-utbk-snbt-2024.png',
    pdfLink:
      'https://www.google.co.id/books/edition/Intensif_Bedah_Materi_Dan_Soal_UTBK_SNBT/Eeg7EQAAQBAJ?hl=en&gbpv=1',
    detailLink: '/detail/7',
    abstract: `Buku kategori panduan belajar yang berjudul Intensif Bedah Materi Dan Soal UTBK-SNBT 2024 merupakan karya dari Yogi Lesmana, S.T., MM, Herman Huang, M.Sc., MBA., A.C. Mahendra. K. Datu, Ph.D. Muhammad Khairul Ihsan, S.Si. Dimas Widianto Ramadhan, S.Si., Cahyarani Paramesti, S.Si., Suci Nadilla Aryandini, S.Pd., Melati Nurjana, S.S., Ananda Restiana Khoirunisa, S.Pd. Buku ke-2 ini khusus penulis kembangkan untuk kebutuhan SNBT-UTBK (Seleksi Nasional Berdasarkan Test – Ujian Tulis Berbasis Komputer) yang dimulai pada tahun 2023. Penulis sangat menyadari betapa kompetitifnya para peminat studi di Perguruan Tinggi Negeri (PTN) saat ini, dan dengan pengembangan kurikulum yang semakin mendekati kebutuhan zaman (Kurikulum Merdeka), buku ini diharapkan akan sangat membantu para calon mahasiswa mempersiapkan ujian dengan lebih baik dan fokus. Materi yang dikembangkan oleh Team Eureka EduTech ini juga telah melalui kurasi yang ketat agar mewakili maksud, tujuan serta karakteristik SNBT-UTBK itu sendiri. Dan dengan pengalaman penulis pada buku pertama (terbit Agustus 2022), penulis sangat yakin bahwa buku ini akan membawa manfaat serta dampak positif bagi para calon mahasiswa untuk mengukur kemampuan literasi serta numerasi mereka dengan lebih presisi.`,
    totalPages: 474,
    publisher: 'Deepublish',
    yearPublished: 2024,
    doi: 'https://www.google.co.id/books/edition/Intensif_Bedah_Materi_Dan_Soal_UTBK_SNBT/Eeg7EQAAQBAJ?hl=en&gbpv=0',
    isTrending: true,
    isNewRelease: false,
  },
  {
    id: 8,
    slug: 'menikmati-proses-dan-hasil-menulis-belajar-menulis-dengan-menulis',
    title: 'Menikmati Proses Dan Hasil Menulis: Belajar Menulis Dengan Menulis',
    author: 'Zulkarnaini Diran',
    publicationDate: 'Jan 2023',
    category: 'E-book',
    thumbnail:
      '/images/pustaka-library/ebook-23-menikmati-proses-dan-hasil-menulis-belajar-menulis-dengan-menulis.png',
    pdfLink:
      'https://www.google.co.id/books/edition/Menikmati_Proses_Dan_Hasil_Menulis_Belaj/frnWEAAAQBAJ?hl=en&gbpv=1',
    detailLink: '/detail/8',
    abstract: `Penulis buku ini benar-benar menikmati hasil-hasil tulisannya. Kenikmatan itu dideskripsikan secara khas. Tentu saja nikmat yang diperolehnya dari hasil menulis, selain bersifat material dan finansial, juga bersifat nonmaterial atau sosial. Semua itu dinukilkan oleh penulis secara khas pula. Mungkin semua orang merasakan dan menikmati hasil menulisnya, tetapi mungkin yang diungkapkan oleh penulis buku ini berbeda dengan kebanyakan penulis lain. Hal itu akan dapat Anda telisik pada setiap subjudul pada buku sederhana ini.`,
    totalPages: 160,
    publisher: 'Penerbit Adab',
    yearPublished: 2023,
    doi: 'https://www.google.co.id/books/edition/Menikmati_Proses_Dan_Hasil_Menulis_Belaj/frnWEAAAQBAJ?hl=en&gbpv=0',
    isTrending: true,
    isNewRelease: false,
  },
  {
    id: 9,
    slug: 'kiat-belajar-di-luar-kelas',
    title: 'Kiat Belajar di Luar Kelas',
    author: 'Joko Subroto',
    publicationDate: 'Agu 2023',
    category: 'E-book',
    thumbnail:
      '/images/pustaka-library/ebook-23-kiat-belajar-di-luar-kelas.png',
    pdfLink:
      'https://www.google.co.id/books/edition/Kiat_Belajar_di_Luar_Kelas/q77QEAAAQBAJ?hl=en&gbpv=1',
    detailLink: '/detail/9',
    abstract: `Belajar tidak hanya dilakukan di dalam kelas. Belajar juga dapat dilakukan di luar kelas, seperti belajar di rumah, perpustakaan pribadi, atau laboratorium pribadi. Namun, tentu saja banyak hal yang dapat menggangu keberhasilan belajar di luar kelas. Bagaimanakah kiat agar belajar di luar kelas berhasil dilakukan? Buku ini memberikan kiat-kiat atau cara jitu agar belajar di luar kelas berhasil dilakukan. Selain itu, buku ini juga menjelaskan cara belajar sesuai tipe-tipe masing-masing siswa, dan memberikan tips dalam menghadapi ujian kelas. Selamat belajar dan sukses!`,
    totalPages: 68,
    publisher: 'Bumi Aksara',
    yearPublished: 2023,
    doi: 'https://www.google.co.id/books/edition/Kiat_Belajar_di_Luar_Kelas/q77QEAAAQBAJ?hl=en&gbpv=0',
    isTrending: true,
    isNewRelease: false,
  },
  {
    id: 10,
    slug: 'top-one-buku-pintar-snbt-2024',
    title: 'TOP ONE Buku Pintar SNBT 2024',
    author:
      'Anggia Morischa, S.Psi, Rudy Purwanto, S.Si, M.Pd, Epi Retnowati, S.Si., Dra. Nurhayati, Lisa Rosaline, S.Pt, M.Pd., Ervan Nugroho Rahmadi, M.Pd.',
    publicationDate: '2023',
    category: 'E-book',
    thumbnail:
      '/images/pustaka-library/ebook-23-top-one-buku-pintar-snbt-2024.png',
    pdfLink:
      'https://www.google.co.id/books/edition/TOP_ONE_Buku_Pintar_SNBT_2024/CnjiEAAAQBAJ?hl=en&gbpv=1',
    detailLink: '/detail/10',
    abstract: `Buku ini menyajikan kumpulan soal yang mencakup berbagai jenis tes, antara lain Tes Potensi Skolastik yang meliputi kemampuan penalaran umum, pengetahuan dan pemahaman umum, memahami bacaan dan menulis, serta pengetahuan kuantitatif. Selain itu, buku ini juga memuat Tes Literasi yang terdiri dari literasi dalam Bahasa Indonesia, literasi dalam Bahasa Inggris, dan penalaran matematika.`,
    totalPages: 520,
    publisher: 'BintangWahyu',
    yearPublished: 2023,
    doi: 'https://www.google.co.id/books/edition/TOP_ONE_Buku_Pintar_SNBT_2024/CnjiEAAAQBAJ?hl=en&gbpv=0',
    isTrending: true,
    isNewRelease: false,
  },
  {
    id: 11,
    slug: 'revolusi-digital-dalam-pendidikan-pemanfaatan-teknologi-ai-artificial-intelligence-untuk-meningkatkan-kualitas-pembelajaran',
    title:
      'REVOLUSI DIGITAL DALAM PENDIDIKAN : PEMANFAATAN TEKNOLOGI AI (ARTIFICIAL INTELLIGENCE) UNTUK MENINGKATKAN KUALITAS PEMBELAJARAN',
    author:
      'Irzon Meiditra, Cut Mutia, Fauziah, Fitra Yuda, M. Rasyid, Riris Agustin, Siti Sahara LubisKarin Oktaviani, S.T',
    publicationDate: 'Jan 2025',
    category: 'Jurnal',
    thumbnail:
      '/images/pustaka-library/jurnal-25-revolusi-digital-dalam-pendidikan-pemanfaatan-teknologi-ai-artificial-intelligence-untuk-meningkatkan-kualitas-pembelajaran.png',
    pdfLink:
      'https://journal.ppmi.web.id/index.php/jpmik/article/view/1930/1287',
    detailLink: '/detail/11',
    abstract: `Perkembangan   teknologi   digital   yang   pesat,   khususnya   dalam   bidang   kecerdasan   buatan   (AI), memberikan  peluang  besar  untuk  meningkatkan  kualitas  pembelajaran  di  dunia  pendidikan.  AI memiliki  potensi   untuk mengubah  proses  belajar-mengajar  dengan   memberikan   solusi  inovatif, seperti  personalisasi  pembelajaran,  analisis  data  akademik,  dan  pengembangan  metode  pengajaran yang  lebih  efektif.  Namun,  penerapan  teknologi  ini  di  institusi  pendidikan,  termasuk  SMA  Negeri  1 Tanah  Putih,  menghadapi  tantangan  seperti  kurangnya  pemahaman  terhadap  AI,  keterbatasan infrastruktur,  dan  minimnya  strategi  pemanfaatan  teknologi  dalam  pembelajaran. Pengabdian kepada  masyarakat  (PkM)  ini melibatkan 104 peserta,  terdiri  dari 102 siswa kelas  sebelas, 2 guru di SMA   Negeri   1   Tanah   Putih yang bertujuan   untuk   mengkaji   dan   mengembangkan   strategi implementasi  teknologi  AI  dalam  pembelajaran  di  SMA  Negeri  1  Tanah  Putih.  Diharapkan  bahwa melalui  pendekatan  yang  tepat,  pemanfaatan  AI  dapat meningkatkan  kualitas  pembelajaran  serta membantu  siswa  dalam  memahami  materi  secara  lebih  mendalam  dan  mandiri.  Program  ini  juga berfokus  pada  penelitian  dan  pengembangan  strategi  untuk  meningkatkan   kualitas  pendidikan melalui penggunaan teknologi AI di SMA Negeri 1 Tanah Putih, menjadikannya lebih  relevan  dengan tuntutan  perkembangan  teknologi  dalam  pendidikan. Hasil  yang  telah  dicapai  dalam  kegiatan  ini mencakup peningkatan  pemahaman  peserta  mengenai  konsep  AI,  implementasi  teknologi  AI  dalam pembelajaran,  serta manfaat  yang  di  hasilkan  untuk  menigkatkan  kualitas  pembelajaran. Selain  itu, kegiatan ini menghasilkan rekomendasi penting nya pelatihan lanjutan yang berkelanjutan tentang AIuntuk   membekali   peserta   dengan   keterampilan   terkini   dalam   pengembangandan   penerapan teknologi saat ini.`,
    totalPages: 8,
    publisher: 'Jurnal Pengabdian Masyarakat Ilmu Komputer',
    yearPublished: 2025,
    doi: 'https://doi.org/10.70248/jpmik.v2i1.1930',
    isTrending: false,
    isNewRelease: true,
  },
  {
    id: 12,
    slug: 'telaah-ragam-artificial-inteligence-ai-dalam-pendidikan',
    title: 'Telaah Ragam Artificial Inteligence (AI) Dalam Pendidikan',
    author:
      'Richa Sucianingtyas, Laukhin Rosyida Falistya, Seftiyan Pujiana, Arditya Prayogi, Sigit Dwi Laksana',
    publicationDate: 'Feb 2025',
    category: 'Jurnal',
    thumbnail:
      '/images/pustaka-library/jurnal-25-telaah-ragam-artificial-inteligence-ai-dalam-pendidikan.png',
    pdfLink: 'https://doi.org/10.5281/zenodo.14874510',
    detailLink: '/detail/12',
    abstract: `Perkembangan teknologi Artificial Intelligence (AI) telah membawa perubahan signifikan dalam berbagai aspek kehidupan, termasuk di bidang pendidikan. Integrasi AI dalam dunia pendidikan menawarkan berbagai keunggulan, seperti peningkatan efisiensi pembelajaran, personalisasi materi, serta otomatisasi tugas administratif. Namun, pemanfaatannya juga menimbulkan tantangan, seperti potensi bias algoritmik, masalah privasi data, dan dampak terhadap interaksi sosial siswa. Artikel ini bertujuan untuk mengkaji ragam penerapan AI dalam pendidikan, mengeksplorasi keunggulan dan kelemahannya, serta memberikan wawasan tentang bagaimana teknologi ini dapat dimanfaatkan secara optimal untuk mendukung proses pembelajaran. Penelitian ini menggunakan metode kualitatif dengan pendekatan studi pustaka, yang melibatkan analisis berbagai sumber literatur terkait implementasi AI dalam pendidikan. Hasil kajian menunjukkan bahwa AI telah diterapkan dalam berbagai bentuk, seperti chatbot untuk interaksi siswa, Natural Language Processing (NLP) untuk analisis bahasa, Augmented Reality (AR) dan Virtual Reality (VR) untuk pengalaman belajar yang lebih imersif, serta Machine Learning untuk personalisasi pembelajaran. Selain itu, Learning Analytics dan Intelligent Tutoring System (ITS) telah membantu meningkatkan efektivitas evaluasi pembelajaran. Implikasi dari kajian ini menunjukkan bahwa meskipun AI menawarkan banyak manfaat bagi dunia pendidikan, implementasinya harus dilakukan secara bijak dengan mempertimbangkan faktor etika, keamanan data, dan keseimbangan peran guru dalam proses pembelajaran. Dengan pemanfaatan yang tepat, AI dapat menjadi alat yang mendukung transformasi pendidikan menuju sistem yang lebih inklusif, efektif, dan adaptif terhadap perubahan zaman.`,
    totalPages: 12,
    publisher: 'Jurnal Ilmiah Multidisiplin',
    yearPublished: 2025,
    doi: 'https://doi.org/10.5281/zenodo.14874510',
    isTrending: false,
    isNewRelease: true,
  },
  {
    id: 13,
    slug: 'analisis-kebijakan-dalam-mengatasi-problematika-pendidikan-untuk-meningkatkan-kualitas-pendidikan-di-indonesia',
    title:
      'Analisis Kebijakan dalam Mengatasi Problematika Pendidikan untuk Meningkatkan Kualitas Pendidikan di Indonesia',
    author:
      'Nur Dahyanti, Sylvi Marsella Diastami, Azra Humaira, Tengku Darmansah',
    publicationDate: 'Jan 2025',
    category: 'Jurnal',
    thumbnail:
      '/images/pustaka-library/jurnal-25-analisis-kebijakan-dalam-mengatasi-problematika-pendidikan-untuk-meningkatkan-kualitas-pendidikan-di-indonesia.png',
    pdfLink:
      'https://ejournal.aripafi.or.id/index.php/Hikmah/article/view/545/590',
    detailLink: '/detail/13',
    abstract: `Pendidikan  merupakan  salah  satu  pilar  utama  dalam  pembangunan  sumber  daya  manusia  di  Indonesia, namun  kualitas  pendidikan masih  menghadapi  berbagai  tantangan,  seperti  ketidakmerataan  akses  dan  rendahnya kualitas  pengajaran.  Penelitian  ini  bertujuan  untuk  menganalisis  kebijakan  pendidikan  yang  telah  diterapkan pemerintah  dalam  upaya  meningkatkan  kualitas  pendidikan  di  Indonesia.  Melalui  pendekatan  kualitatif,  analisis kebijakan dilakukan untuk mengidentifikasi faktor-faktor yang mempengaruhi efektivitas kebijakan serta dampaknya terhadap  masyarakat. Hasil analisis  menunjukkan bahwa  meskipun terdapat  program-program  seperti  wajib belajar dan  peningkatan  kompetensi  guru,  kesenjangan  antara  kebijakan  yang  dirumuskan  dan  implementasinya  masih menjadi masalah utama. Oleh karena itu, diperlukan pendekatan yang lebih inklusif dan partisipatif dalam perumusan kebijakan pendidikan untuk memastikan bahwa setiap kebijakan yang diambil mampu menjawab kebutuhan lokal dan meningkatkan kualitas pendidikan secara keseluruhan.`,
    totalPages: 14,
    publisher: 'Jurnal Studi Pendidikan Agama Islam',
    yearPublished: 2025,
    doi: 'https://doi.org/10.61132/hikmah.v2i1.545',
    isTrending: false,
    isNewRelease: true,
  },
  {
    id: 14,
    slug: 'transformasi-perkembangan-kurikulum-di-indonesia',
    title: 'Transformasi Perkembangan Kurikulum di Indonesia',
    author: 'Eka Paramita, Aminullah Aminullah, Desi Ratnasari, Asmaul Husna',
    publicationDate: 'Jan 2025',
    category: 'Jurnal',
    thumbnail:
      '/images/pustaka-library/jurnal-25-transformasi-perkembangan-kurikulum-di-indonesia.png',
    pdfLink:
      'https://jurnal.bimaberilmu.com/index.php/jppi/article/view/976/567',
    detailLink: '/detail/14',
    abstract: `Penelitian ini bertujuan untuk menganalisis sejarah perkembangan kurikulum di Indonesia, menyoroti pentingnya kurikulum sebagai pilar utama pendidikan yang mendukung proses pembelajaran dengan melalui pertimbangan dalam kebijakan kurikulum di Indonesia dengan fokus pada perubahan yang terjadi dalam sistem pendidikan serta dampaknya pada kualitas pembelajaran. Adapaun metode yang digunakan dalam penelitian ini adalah pendekatan kualitatif dengan analisis deskriptif, dengan teknik pengumpulan data melalui studi literatur terhadap beberapa sumber data yang mendukung penelitian ini. Hasil penelitian ini menunjukkan bahwa transformasi kurikulum di Indonesia mengalami perubahan dengan beberapa fase yang signifikan, bermula pada penekanan terhadap pengetahuan faktual hingga pada pendekatan yang lebih holistik dan berbasis kompetensi. Selain itu penelitian ini juga mengidentifikasi beberapa asas dan faktor-faktor yang mempengaruhi perkembangan kurikulum di Indonesia. Secara keseluruhan, transformasi perkembangan kurikulum di Indonesia diharapkan mampu meningkatkan kualitas pendidikan dan keterkaitan antara kurikulum yang diharuskan dapat memenuhi kebutuhan masyarakat dan selaras dengan perkembangan ilmu pengetahuan serta tetap mengikuti perkembangan teknologi yang semakin pesat.`,
    totalPages: 16,
    publisher: 'Jurnal Pendidikan dan Pembelajaran Indonesia (JPPI)',
    yearPublished: 2025,
    doi: 'https://doi.org/10.53299/jppi.v5i1.976',
    isTrending: false,
    isNewRelease: true,
  },
  {
    id: 15,
    slug: 'pendidikan-indonesia-masih-buruk',
    title: 'Pendidikan Indonesia Masih Buruk?',
    author:
      'Putri Amalya Rizkianti, Masduki Asbari, Nandita Putri Priambudi, Selvy Alhani Juni Asri',
    publicationDate: 'Apr 2024',
    category: 'Jurnal',
    thumbnail:
      '/images/pustaka-library/jurnal-24-pendidikan-indonesia-masih-buruk.png',
    pdfLink: 'https://jisma.org/index.php/jisma/article/view/942/169',
    detailLink: '/detail/15',
    abstract: `Tujuan dari artikel ini yaitu untuk menganalisis video darichannel Youtube Satu Persen yang berjudul KenapaPendidikan  Indonesia  Buruk?  Pendidikan  Indonesia  dibanding  Dunia.  Metode  yang  digunakan  dalam artikel  ini  yaitu  metode  kualitatif  karena  metode  ini  sangat  kerap  dengan  hasilnya  yaitu  sebuah  analisis  dan kesimpulan dalam artikel ini  membahas tentang masalah sistem Pendidikan saat ini, dan membahas nilaiPISA (Programme for International Student Assessment) negara indonesia rendah dibandingkan dengan negara lain. Dan  juga  membahas  solusi  bagaimana  agar pendidikan Indonesia  lebih  membaik.  Karena  Pendidikan  itu  juga sangat  penting  bagi  manusia  agar  tidak  tertinggal  akan  perkembangan  zaman  dan  menambah  pengetahuan mereka. Dan juga  perlunya pengembagan keahlian karena di era  sekarang industri berkembang dengan sangat cepat maka dari itu diperlukannya keahlian yang baik agar tidak banyaknya pengangguran.`,
    totalPages: 4,
    publisher: 'JISMA Journal Of Information Systems and Management',
    yearPublished: 2024,
    doi: 'https://jisma.org/index.php/jisma/article/view/942',
    isTrending: true,
    isNewRelease: false,
  },
  {
    id: 16,
    slug: 'kasus-bullying-dunia-pendidikan-di-indonesia-dari-perspektif-media-dan-pemberitaannya',
    title:
      'Kasus Bullying Dunia Pendidikan di Indonesia dari Perspektif Media dan Pemberitaannya',
    author: 'Chairani Asyifah, Mas Agus Firmansyah, Dwi Aji Budiman',
    publicationDate: 'Jan 2024',
    category: 'Jurnal',
    thumbnail:
      '/images/pustaka-library/jurnal-24-kasus-bullying-dunia-pendidikan-di-indonesia-dari-perspektif-media-dan-pemberitaannya.png',
    pdfLink:
      'https://jurnal.syntaxliterate.co.id/index.php/syntax-literate/article/view/14855/9540',
    detailLink: '/detail/16',
    abstract: `Kasus bullying di kalangan pelajar Indonesia hingga kini masih menjadi permasalahan dalam dunia pendidikan Indonesia. Banyaknya kasus bullying yang terjadi di sekolah Indonesia yang terkuak ke masyarakat, membuat media Indonesia beramai-ramai memberitakan tindakan perundungan yang ada di dunia pendidikan Indonesia. Berita yang disajikan oleh media terdiri dari berbagai jenjang pendidikan, mulai dari SD hingga SMA/SMK dan kebanyakan media massa Indonesia dalam memberitakan kasus perundungan di lingkungan sekolah diberitakan secara berkala. Tujuan penelitian untuk melihat dampak dari berita-berita mengenai kasus perundungan yang diangkat oleh media Indonesia dapat mengurangi populasi pelaku tindakan bullying atau semakin meningkatkan tindakan kasus perundungan di dunia pendidikan Indonesia. Penelitian ini menggunakan pendekatan kualitatif deskriptif dengan metode studi dokumentasi untuk mengumpulkan data-data korban bullying dan berita yang telah diangkat oleh media massa Indonesia di kalangan pelajar. Berdasarkan hasil penelitian, media massa Indonesia telah berupaya dalam menangani kasus perundungan di kalangan pelajar di Indonesia, berupa edukasi tentang dampak dari bullying dan data korban dari tindakan bullying. Tetapi hal ini tidak terlalu memberikan efek besar untuk mengurangi tindak kekerasan bullying di dunia pendidikan Indonesia, karena setelah viralnya beberapa kasus bullying di media pemberitaan Indonesia ternyata kasus bullying di lingkungan sekolah tetap terjadi.`,
    totalPages: 10,
    publisher: 'Syntax Literate: Jurnal Ilmiah Indonesia',
    yearPublished: 2024,
    doi: 'https://jurnal.syntaxliterate.co.id/index.php/syntax-literate/article/view/14855',
    isTrending: false,
    isNewRelease: false,
  },
  {
    id: 17,
    slug: 'filosofi-pendidikan-yang-diusung-oleh-ki-hadjar-dewantara-dan-evolusi-pendidikan-di-indonesia',
    title:
      'Filosofi Pendidikan Yang diusung Oleh Ki Hadjar Dewantara dan Evolusi Pendidikan di Indonesia',
    author: 'Tia Basana Hutagalung, Liesna Andriany',
    publicationDate: 'Jun 2024',
    category: 'Jurnal',
    thumbnail:
      '/images/pustaka-library/jurnal-24-filosofi-pendidikan-yang-diusung-oleh-ki-hadjar-dewantara-dan-evolusi-pendidikan-di-indonesia.png',
    pdfLink:
      'https://journal.aspirasi.or.id/index.php/morfologi/article/view/615/600',
    detailLink: '/detail/17',
    abstract: `Dasar pendidikan adalah aspirasi kemanusiaan di seluruh dunia, oleh karena itu dalam menghadapi permasalahan pendidikan diperlukan pemecahan yang kompleks dengan filosofi agar solusi yang dihasilkan dapat memberikan manfaat bagi seluruh kalangan masyarakat.Salah satu tokoh yang memiliki pandangan filosofi yang kuat mengenai pendidikan adalah Ki Hadjar Dewantara. Ki Hadjar Dewantara adalah seorang bangsawan dari lingkungan Kraton Yogyakarta memegang teguh kepedulian yang tinggi terhadap pengembangan pendidikan. Pandangan filosofi yang dikemukakan oleh Ki Hadjar Dewantara telah menjadi landasan bagi pengembangan pendidikan di Indonesia. Ki Hadjar Dewantara mengungkapkan bahwa hakikat pendidikan adalah usaha untuk menginternalisasikan nilai-nilai budaya ke dalam diri anak dengan tujuan membentuk mereka menjadi manusia yang utuh, baik dari segi jiwa maupun rohaninya. Filosofi pendidikan ini dikenal dengan istilah "Sistem Among," yang menekankan pada kemampuan dasar anak untuk mengatasi masalah  yang  mereka  hadapi  dengan  memberikan  kebebasan  berpikir  yang  luas.  Ki  Hadjar  Dewantara merumuskan filosofinya dengan menerapkan kebudayaan asli Indonesia, sebaliknya mengambil nilai-nilai Barat secara  selektif  menyesuaikan  dengan  teori  trikon,  lalu  mengadaptasikannya  secara  bijaksana.  Ki  Hadjar Dewantara juga memberikan beberapa kontribusi bagi pendidikan Indonesia adalah mencakup penerapan trilogi kepemimpinan dalam pendidikan, tri pusat pendidikan dan sistem paguron. Pendidikan sebagai upaya untuk mengembangkan potensi manusiawi peserta didik, baik secara fisik, cipta, rasa, dan karsanya, agar potensi tersebut dapat terwujud dan bermanfaat bagi kehidupannya.`,
    totalPages: 9,
    publisher: 'Jurnal Ilmu Pendidikan, Bahasa, Sastra dan Budaya (MORFOLOGI)',
    yearPublished: 2024,
    doi: 'https://doi.org/10.61132/morfologi.v2i3.615',
    isTrending: false,
    isNewRelease: false,
  },
  {
    id: 18,
    slug: 'perkembangan-kurikulum-terhadap-kualitas-pendidikan-di-indonesia',
    title: 'Perkembangan Kurikulum Terhadap Kualitas Pendidikan di Indonesia',
    author: 'Sri Rejeki Setiyorini, Deni Setiawan',
    publicationDate: 'Okt 2023',
    category: 'Jurnal',
    thumbnail:
      '/images/pustaka-library/jurnal-23-perkembangan-kurikulum-terhadap-kualitas-pendidikan-di-indonesia.png',
    pdfLink: 'https://edu.pubmedia.id/index.php/jtp/article/view/27/35',
    detailLink: '/detail/18',
    abstract: `Pendidikan memainkan peran penting sebagai agen sosial. Tujuan Pendidikan Nasional adalah diharapkan menghasilkan masyarakat Indonesia yang beragama dan bermoral, mampu menguasai pengetahuan dan keterampilan, sehat secara fisik dan spiritual, memiliki kepribadian yang baik, dan bertanggung jawab. Untuk mencapai tujuan ini, yang perlu dikembangkan adalah kurikulum pendidikan karena satu dimensi yang tidak dapat dipisahkan dari perkembangan dunia pendidikan nasional di masa depan adalah kebijakan terkait kurikulum. Kurikulum sebagai bagian penting dari pendidikan memiliki posisi strategis dalam dunia pendidikan. Tujuan dari penelitian ini adalah untuk mengevaluasi perkembangan kurikulum terhadap kualitas pendidikan di Indonesia. Jenis penelitian ini adalah studi literatur menggunakan metode kualitatif. Hasil dari penelitian ini adalah perubahan kurikulum dapat memiliki dampak positif dan negatif pada kualitas pendidikan. Salah satu dampak positif dari perubahan kurikulum ini adalah bahwa siswa dapat belajar untuk mengikuti perkembangan yang semakin maju. Sementara itu, salah satu dampak negatif adalah bagi siswa, karena perubahan kurikulum yang cepat dapat menimbulkan masalah baru seperti penurunan prestasi siswa, karena siswa belum mampu mengikuti sistem pembelajaran yang baru.`,
    totalPages: 12,
    publisher: 'JTP: Jurnal Teknologi Pendidikan',
    yearPublished: 2023,
    doi: 'https://doi.org/10.47134/jtp.v1i1.27',
    isTrending: true,
    isNewRelease: false,
  },
  {
    id: 19,
    slug: 'perkembangan-pendidikan-di-indonesia',
    title: 'Perkembangan Pendidikan di Indonesia',
    author: 'Syamsul Hidayat, Siti Nurjanah, Erry Utomo, Agung Purwanto',
    publicationDate: 'Apr 2023',
    category: 'Jurnal',
    thumbnail:
      '/images/pustaka-library/jurnal-23-perkembangan-pendidikan-di-indonesia.png',
    pdfLink: 'https://doi.org/10.30997/jtm.v7i1.7167',
    detailLink: '/detail/19',
    abstract: `Pendidikan telah ada di Indonesia sejak tahun 1901 ketika terjadi penjajahan yang dilakukan oleh Belanda dan Jepang. Pada masa itu Belanda dan Jepang membangun berbagai sekolah untuk masyarakat. Tujuan penelitian ini untuk menganalisis perkembangan pendidikan di Indonesia. Metode penelitian ini adalah systematic literature review. Hasil menunjukkan bahwa jenjang pendidikan pada sistem pendidikan di Indonesia yaitu pendidikan rendah, pendidikan menengah pertama, pendidikan menengah atas, dan pendidikan tinggi. Sejak 1947-2022 sudah ada beberapa kali perubahan kurikulum. Pada masa orde lama ditetapkan perubahan kurikulum sebanyak 3 kali. Pada masa orde baru ditetapkan perubahan kurikulum sebanyak 4 kali. Pada masa reformasi ditetapkan perubahan kurikulum sebanyak 4 kali. Pendidikan Islam di Indonesia dilakukan secara non formal dan formal saat Islam masuk ke Indonesia. Kesimpulan dari hasil penelitian ini adalah sejak tahun 1947-2022 sudah dilakukan 11 kali perubahan kurikulum dan pendidikan Islam terus berkembang sampai saat ini karena banyak masyarakat memeluk agama Islam.`,
    totalPages: 16,
    publisher: 'TADBIR MUWAHHID',
    yearPublished: 2023,
    doi: 'https://doi.org/10.30997/jtm.v7i1.7167',
    isTrending: true,
    isNewRelease: false,
  },
  {
    id: 20,
    slug: 'pelatihan-penggunaan-artificial-intelligence-ai-terhadap-perkembangan-teknologi-pada-pembelajaran-siswa-sma-10-sukarami-kota-bengkulu',
    title:
      'Pelatihan Penggunaan Artificial Intelligence (AI) Terhadap Perkembangan Teknologi Pada Pembelajaran Siswa Sma 10 Sukarami Kota Bengkulu',
    author: 'Siti Hanila, Muhammad Afif Alghaffaru',
    publicationDate: 'Sep 2024',
    category: 'Jurnal',
    thumbnail:
      '/images/pustaka-library/jurnal-23-pelatihan-penggunaan-artificial-intelligence-ai-terhadap-perkembangan-teknologi-pada-pembelajaran-siswa-sma-10-sukarami-kota-bengkulu.png',
    pdfLink: 'https://jurnal.unived.ac.id/index.php/jdm/article/view/4890/3629',
    detailLink: '/detail/20',
    abstract: `Kecerdasan  Buatan  mengacu  pada  kemampuan  sistem  komputer  untuk  melakukan tugas  yang  biasanya  memerlukan  kecerdasan  manusia,  seperti  pemrosesan  bahasa alami,  pengambilan  keputusan,  belajar  dari  pengalaman,  dan  tugas  kognitif  lainnya. Dalam banyak kasus, penggunaan teknologi AI dalam pembelajaran memerlukan akses yang baik terhadap perangkat keras dan jaringan internet. Namun, tidak semua siswa memiliki  akses  yang  setara  terhadap  perangkat  dan  koneksi  yang  diperlukan.  Hal  ini dapat memperdalam  kesenjangan  pendidikan  antara  siswa  yang  mampu  mengakses teknologi  dan  yang  tidak.  Ada  pun  metode  Penelitian  Supervised  Machine  Learning, Deep  Learning,  NLP,  dan  masih  banyak  lagi.  Dengan  pelatihan  penggunaan  AI  bagi siswa  telah  membuka  lembar  baru  bagi  siswa  dimana  dengan  ada  nya  AI  ini  telah banyak membantu siswa mencari Informasi dengan cepat dan lebih mudah, dan dengan nya AI ini telah memberi dampak besar bagi siswa mau pun pelajar. Kecerdasan Buatan (AI) telah membuka pintu menuju era teknologi yang mengubahcara kita berinteraksi dengan  dunia.  Perkembangan  AI  telah  mempengaruhi  banyak  Aspek  kehidupan termasuk  industri,  pendidikan,  kesehatan,  dan  lainya.  Dengan  kemapuan  untuk memproses  data  besar,   mengindentifikasi  pola  yang  kompleks,  dan  mengambil keputusan secara otomastis, AI telah membantu mengatasi tantangan dan memberikan peluag  baru.  Namun,  perkembangan  ini  juga  menghadirkantantangan  baru,  seperti etika,  privasi  data  dan  dampak  terhadap  lapangan  pekerjaan. Masalah  dari    Melihat potensi  AI  dalam  mengubah lanskap  pekrjaan,  penting  bagi  individu  untuk  terus memperbarui  keterampilan  mereka.  Pelatihan  berkelanjutan  dalam  bidang  teknologi, analisis  data,  dan  pemrograman  dapat  membantu  orang  mempersiapkan  diri  untuk perkerjaan masa depan yang lebih terotomatisasi.`,
    totalPages: 6,
    publisher: 'Jurnal Dehasen Mengabdi',
    yearPublished: 2024,
    doi: 'https://doi.org/10.37676/jdm.v2i2.4890',
    isTrending: false,
    isNewRelease: false,
  },
];
